export const menus = [
    {
        id: '1',
        parent_id: '0',
        name: '概要',
        icon_id: 'dashboard',
        level: '1',
        route: '/dashboard',
        showSide: true,
    },
    {
        id: '2',
        parent_id: '0',
        name: '数据源',
        icon_id: 'database',
        level: '1',
        route: '/dataSource',
        showSide: true,
    },
    {
        id: '3',
        parent_id: '0',
        name: '规则配置',
        icon_id: 'setting',
        level: '1',
        route: '/ruleSet',
        showSide: true,
    },
    {
        id: '4',
        parent_id: '0',
        name: '工作流',
        icon_id: 'database',
        level: '1',
        route: '/workFlow',
        showSide: true,
    },
];
